name: cfdml_era5_download
channels:
  - conda-forge
dependencies:
  - python=3.11
  - pip
  - numpy
  - xarray==2024.11.0
  - zarr
  - dask
  - netcdf4
  - ipykernel
  - scipy
  - pandas
  - requests
  - aiohttp
  - matplotlib
  - intel-openmp=2024.2.1
